name: Catalogue-CI/CD

on:
    workflow_dispatch:
        inputs:
            app_name:
                description: 'application name'
                required: true
                default : 'catalogue'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:


            - name: Git Checkout
              uses: actions/checkout@v3

            - name: Get Version Number
              id: get_version
              run: | 
              app_version = $(node -p "require('./package.json').version")
              echo app_version: ${app_version}

            - name: Setup Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: '16'

            - name: Install Dependencies
              run: |
                npm install
            
            - name: Satic Code Analysis (Sonarqube)
              run: echo "Sonar Scan"
            
            - name: Build
              run: |
              zip_file= "${{ github.events.inputs.app_name }}-${{ steps.get_version.outputs.app_version}}.zip"
              echo Creating zip file: ${zip_file}
            

